# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jpmobile-ipaddresses"
  s.version = "0.0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Shin-ichiro OGAWA"]
  s.date = "2012-06-05"
  s.description = "Carrier IP Address List for jpmobile"
  s.email = "rust.stnard@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "jpmobile-ipaddresses.gemspec",
    "lib/jpmobile-ipaddresses.rb",
    "lib/jpmobile/mobile/ip_addresses/abstract_ip_addresses.rb",
    "lib/jpmobile/mobile/ip_addresses/au.rb",
    "lib/jpmobile/mobile/ip_addresses/docomo.rb",
    "lib/jpmobile/mobile/ip_addresses/emobile.rb",
    "lib/jpmobile/mobile/ip_addresses/softbank.rb",
    "lib/jpmobile/mobile/ip_addresses/willcom.rb"
  ]
  s.homepage = "http://github.com/jpmobile/jpmobile-ipaddresses"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Carrier IP Address List for jpmobile"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 1.4.0"])
    else
      s.add_dependency(%q<jeweler>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 1.4.0"])
  end
end

